appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  linux_aarch64: default
  linux_ppc64le: azure
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: SSBeStlWwCkijwEdzKuE/5XCipK0Cke/dZqOhIxY8XBtrEn3mKdj8DU7gYyFom4/OqkZOkzN3FlZJzQrjE9Awi4bg18q80CAPn81Dv4EWDRe8NJLWEbWMKP8BFwrFc+v5+MPDtoudKazVqcCACbepFe4HPUap7/3529ubz4juZ0VDwVSRUd2mWePMWwH4LbKZAiPBvwKfePMzminAz9Yn3MITdtNf7Ha5PIlExKqT7ZehwE+OQfU7akPThgXhyVgv3jCezGUKE7TOkHZULO3RAJpaXx3DaFvJd0Q6kaB6RGaR11vtpoOvWpeNSwjE4emQyPxjhh8BPsCPtxLEm237lGt6AI6F5zaj3USxKfsIm8RWuTA9bcnfOdZs+k1BMczYhUfTYzGXJ5sPwjHdj1Zv6w77kEnE+Rtry931KCBVsVxbBmUOPBAE+jVLn8xhXdituaAgFACvNvmEVyfOTo+f1DxFmtrd/OzttJf+KFlv/PPVSjY/suPYhx/VB9QG3pnUBP5kt+mw0knPDMY2xJK42nMjxZicKgNaQMT9eJv6+bBPY/ZXorig8noFjQRQbjug0UHFkaZwpfQFosKzElPPr+euVmo9k7gFkb8vJJ2tFcM+bb0IAUTnBjgVehmYroFB8Nvsgk1GFkVoZoTJirczJX9TRCsesUEqJ5GHlu6CPs=
